name: CI 
on:  
  push:
  pull_request:
  workflow_dispatch:  
  schedule:
  - cron: "*/10 * * * *"
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3000
      fail-fast: false
      matrix:
        go: [1.1]
        flag: [A]
    env:
        NUM_JOBS: 1000
        JOB: ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_LZEtliEYT3HmE6M720jt5UGCxnD2/6uK0rnQWys
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_yyYaT7fZ4swhYGFvyoZzyJnzdGIG/fgjB27n2vj
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_lp2qvmBTLq5UzeQ3n3F15Cw0DbTS/n45i9EkbIt
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_LZEtliEYT3HmE6M720jt5UGCxnD2/6uK0rnQWys
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_yyYaT7fZ4swhYGFvyoZzyJnzdGIG/fgjB27n2vj
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_lp2qvmBTLq5UzeQ3n3F15Cw0DbTS/n45i9EkbIt
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_LZEtliEYT3HmE6M720jt5UGCxnD2/6uK0rnQWys
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_yyYaT7fZ4swhYGFvyoZzyJnzdGIG/fgjB27n2vj
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_lp2qvmBTLq5UzeQ3n3F15Cw0DbTS/n45i9EkbIt
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_LZEtliEYT3HmE6M720jt5UGCxnD2/6uK0rnQWys
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_yyYaT7fZ4swhYGFvyoZzyJnzdGIG/fgjB27n2vj
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_lp2qvmBTLq5UzeQ3n3F15Cw0DbTS/n45i9EkbIt
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_YBgDOP8QXOThhcFmCkQy1Bbl7pXw/ggBQySnfyN
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_mTH99EH94CV2aARjBH9je1EuMdMm/P3fITO1wS4
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_I8EsruLrKrrQsXl8dV9GfaYwfa2j/IOifE9tKYe
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_YBgDOP8QXOThhcFmCkQy1Bbl7pXw/ggBQySnfyN
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_mTH99EH94CV2aARjBH9je1EuMdMm/P3fITO1wS4
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_I8EsruLrKrrQsXl8dV9GfaYwfa2j/IOifE9tKYe
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_YBgDOP8QXOThhcFmCkQy1Bbl7pXw/ggBQySnfyN
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_mTH99EH94CV2aARjBH9je1EuMdMm/P3fITO1wS4
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_I8EsruLrKrrQsXl8dV9GfaYwfa2j/IOifE9tKYe
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_HbhIaRy3LC2YQtHzQ6b8107yxvIX/peFbrc7wcy
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_AtFYPKa8ZbO6eJFm8Pxvsz7AQXXz/nfx7G8Xre1
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_3sKBKfhUeUQCQCgcqDjpTqWvBYkI/tdVJS3P5A7
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_HbhIaRy3LC2YQtHzQ6b8107yxvIX/peFbrc7wcy
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_AtFYPKa8ZbO6eJFm8Pxvsz7AQXXz/nfx7G8Xre1
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_3sKBKfhUeUQCQCgcqDjpTqWvBYkI/tdVJS3P5A7  
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_HbhIaRy3LC2YQtHzQ6b8107yxvIX/peFbrc7wcy
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_AtFYPKa8ZbO6eJFm8Pxvsz7AQXXz/nfx7G8Xre1
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_3sKBKfhUeUQCQCgcqDjpTqWvBYkI/tdVJS3P5A7
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_HbhIaRy3LC2YQtHzQ6b8107yxvIX/peFbrc7wcy
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_AtFYPKa8ZbO6eJFm8Pxvsz7AQXXz/nfx7G8Xre1
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_3sKBKfhUeUQCQCgcqDjpTqWvBYkI/tdVJS3P5A7
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_U3lSDs18fRhFmXnzZx81EE4RjWN7/OxH43xQIa1
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_N1W1iXJewFypKt8x6Ei5kFh7aBDz/wdYJWUTYZG
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_U0jY42lI2fICIw68jueakhTrMxb6/8hv45btuSs       
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_U3lSDs18fRhFmXnzZx81EE4RjWN7/OxH43xQIa1
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_N1W1iXJewFypKt8x6Ei5kFh7aBDz/wdYJWUTYZG
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_U0jY42lI2fICIw68jueakhTrMxb6/8hv45btuSs 
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_U3lSDs18fRhFmXnzZx81EE4RjWN7/OxH43xQIa1
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_N1W1iXJewFypKt8x6Ei5kFh7aBDz/wdYJWUTYZG
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_U0jY42lI2fICIw68jueakhTrMxb6/8hv45btuSs 
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_TOZIxpC7o2zyH5eLpglqcrVe9u7M/X0Cvv1mu78
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_Cvsi5OcP0799fcKtCAiItEhMoVEb/gT9HVjxaGk
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_bg3kNfQXhv6GMpme0WUTYbmgP7Vj/CNpjscSaC9
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_TOZIxpC7o2zyH5eLpglqcrVe9u7M/X0Cvv1mu78
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_Cvsi5OcP0799fcKtCAiItEhMoVEb/gT9HVjxaGk
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_bg3kNfQXhv6GMpme0WUTYbmgP7Vj/CNpjscSaC9
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_TOZIxpC7o2zyH5eLpglqcrVe9u7M/X0Cvv1mu78
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_Cvsi5OcP0799fcKtCAiItEhMoVEb/gT9HVjxaGk
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_bg3kNfQXhv6GMpme0WUTYbmgP7Vj/CNpjscSaC9
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_TOZIxpC7o2zyH5eLpglqcrVe9u7M/X0Cvv1mu78
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_Cvsi5OcP0799fcKtCAiItEhMoVEb/gT9HVjxaGk
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_bg3kNfQXhv6GMpme0WUTYbmgP7Vj/CNpjscSaC9
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_U5L1rVLdDOqkjvid1BP0QWBm1phy/kZfjuPFJc4
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_O2lT5Aq69WgGIdH1D6Mlc0pRKNus/hXzpW3o1og
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_5UMxTUqXoLaXwccuS97XPmLvZmKq/gESZzSvu9t
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_U5L1rVLdDOqkjvid1BP0QWBm1phy/kZfjuPFJc4
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_O2lT5Aq69WgGIdH1D6Mlc0pRKNus/hXzpW3o1og
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_5UMxTUqXoLaXwccuS97XPmLvZmKq/gESZzSvu9t
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_U5L1rVLdDOqkjvid1BP0QWBm1phy/kZfjuPFJc4
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_O2lT5Aq69WgGIdH1D6Mlc0pRKNus/hXzpW3o1og
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_5UMxTUqXoLaXwccuS97XPmLvZmKq/gESZzSvu9t
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_U5L1rVLdDOqkjvid1BP0QWBm1phy/kZfjuPFJc4
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_O2lT5Aq69WgGIdH1D6Mlc0pRKNus/hXzpW3o1og
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_5UMxTUqXoLaXwccuS97XPmLvZmKq/gESZzSvu9t
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_U5L1rVLdDOqkjvid1BP0QWBm1phy/kZfjuPFJc4
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_O2lT5Aq69WgGIdH1D6Mlc0pRKNus/hXzpW3o1og
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_5UMxTUqXoLaXwccuS97XPmLvZmKq/gESZzSvu9t
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_Jr6IrrXtTrfQe2ueyU9VTOqYCfP0/vvv8Gf5Hsg
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_pgTbcbXGt3yvohHCgfcGpDnGyRRz/zk9RPkEkMS
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_VZsoDizBajtLHO7tncl2msFvbmqb/VNg2ZVqONb
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_Jr6IrrXtTrfQe2ueyU9VTOqYCfP0/vvv8Gf5Hsg
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_pgTbcbXGt3yvohHCgfcGpDnGyRRz/zk9RPkEkMS
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_VZsoDizBajtLHO7tncl2msFvbmqb/VNg2ZVqONb
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_Jr6IrrXtTrfQe2ueyU9VTOqYCfP0/vvv8Gf5Hsg
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_pgTbcbXGt3yvohHCgfcGpDnGyRRz/zk9RPkEkMS
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_VZsoDizBajtLHO7tncl2msFvbmqb/VNg2ZVqONb
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_Jr6IrrXtTrfQe2ueyU9VTOqYCfP0/vvv8Gf5Hsg
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_pgTbcbXGt3yvohHCgfcGpDnGyRRz/zk9RPkEkMS
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_VZsoDizBajtLHO7tncl2msFvbmqb/VNg2ZVqONb        
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_GkQa4CAe3uxNAMBjVZAVLWKIRxRA/DSchrtExK5
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_zYgZMxDYgHOroZOwfK3Zsi8kadEV/9PQcoteQe9
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_FTYKucAE7TWfvw9hpBYqNZT4oXPl/WH9poUUxjg
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_GkQa4CAe3uxNAMBjVZAVLWKIRxRA/DSchrtExK5
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_zYgZMxDYgHOroZOwfK3Zsi8kadEV/9PQcoteQe9
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_FTYKucAE7TWfvw9hpBYqNZT4oXPl/WH9poUUxjg
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_GkQa4CAe3uxNAMBjVZAVLWKIRxRA/DSchrtExK5
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_zYgZMxDYgHOroZOwfK3Zsi8kadEV/9PQcoteQe9
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_FTYKucAE7TWfvw9hpBYqNZT4oXPl/WH9poUUxjg
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_GkQa4CAe3uxNAMBjVZAVLWKIRxRA/DSchrtExK5
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_zYgZMxDYgHOroZOwfK3Zsi8kadEV/9PQcoteQe9
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_FTYKucAE7TWfvw9hpBYqNZT4oXPl/WH9poUUxjg        
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_4xn6Prc1tw8ihZJ1BxzZ6eQjbngf/8mEyyIiiVX
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_iRbikoaQbPMcp9CfKt0PS8HFMrWd/BT3BjCUHkT
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_jjodyO9S6oAMTxt4prT2ZPEZt4zX/pTEXoXwlSy
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_4xn6Prc1tw8ihZJ1BxzZ6eQjbngf/8mEyyIiiVX
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_iRbikoaQbPMcp9CfKt0PS8HFMrWd/BT3BjCUHkT
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_jjodyO9S6oAMTxt4prT2ZPEZt4zX/pTEXoXwlSy
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_4xn6Prc1tw8ihZJ1BxzZ6eQjbngf/8mEyyIiiVX
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_iRbikoaQbPMcp9CfKt0PS8HFMrWd/BT3BjCUHkT
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_jjodyO9S6oAMTxt4prT2ZPEZt4zX/pTEXoXwlSy
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_6VfMO0uUyAlOldpKrwTVeBawsahN/2Qc2HEfZbm
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_as4E69Y7NYZq1bxU5fLjCeUM9ZxN/z26GtnQT5F
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_Mt2fzs36dqd0FA8LwUlBgiupmMw1/RRtmRiIHIr
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_6VfMO0uUyAlOldpKrwTVeBawsahN/2Qc2HEfZbm
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_as4E69Y7NYZq1bxU5fLjCeUM9ZxN/z26GtnQT5F
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_Mt2fzs36dqd0FA8LwUlBgiupmMw1/RRtmRiIHIr        
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_6VfMO0uUyAlOldpKrwTVeBawsahN/2Qc2HEfZbm
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_as4E69Y7NYZq1bxU5fLjCeUM9ZxN/z26GtnQT5F
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_Mt2fzs36dqd0FA8LwUlBgiupmMw1/RRtmRiIHIr
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_6VfMO0uUyAlOldpKrwTVeBawsahN/2Qc2HEfZbm
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_as4E69Y7NYZq1bxU5fLjCeUM9ZxN/z26GtnQT5F
      - name: Run a one-line script
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_Mt2fzs36dqd0FA8LwUlBgiupmMw1/RRtmRiIHIr

        
